### ISSUE TITLE
items from slack

### ISSUE THREAD

**Issue by abalkin** [kparc/ref#10]
## TODO

- [ ] fix auto-linker (@chrispsn)
- [ ] write a short python script `test.py` that tests `refcard_detail.md` against shakti-python's md checker
- [ ] add the datetime somewhere to the refcard page
- [ ] get the md, k.txt and l.txt building in a script instead of client-side
- [ ] find somewhere suitable for setting up an auto-build server and have it detect webhook events when there are new commits in `kparc/box` (so it can trigger a build). Ideally not someone’s personal server. Have it integrated with defcon if fails; or at least email
- [ ] final task: update the build script to get the auto-linker working during page build; alert if any of the links fail or the `test.py` script fails

**Comment by chrispsn** [comment]
Auto-linker is fixed.

**Comment by chrispsn** [comment]
`validate.py` committed to repo.
